[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "promptlab"
version = "0.1.11"
description = "PromptLab is a free, lightweight, open-source experimentation tool for Gen AI applications."
readme = "README.md"
authors = [{name = "ra1han", email = "hello@pl.com"}]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic>=2.0.0",
    "requests>=2.25.0",
    "openai>=1.60.0",
    "flask[async]>=3.0.0",
    "flask-cors>=5.0.0",
    "click>=8.0.0",
    "ollama>=0.4.7",
    "aiohttp>=3.8.0",
    "fastapi>=0.100.0",
    "numpy",
    "python-dotenv>=1.0.0",
    "rouge-score>=0.1.2",
    "art>=6.5",
    "setuptools",
    "uvicorn[standard]>=0.18.0",
    "sqlalchemy",
    "alembic>=1.8.0",
    "passlib",
    "python-jose",
    "python-multipart",
    "bcrypt==4.1.2",
    "uvloop>=0.17.0; sys_platform != 'win32'",
    "httptools>=0.5.0; sys_platform != 'win32'",
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/imum-ai/promptlab"
Issues = "https://github.com/imum-ai/promptlab/issues"

[tool.setuptools.package-data]
promptlab = ["web/*.html", "alembic.ini", "migrations/*", "migrations/**/*"]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
promptlab = "promptlab._cli:promptlab"
